const metodosString = [
  { text: 'at()', ref: 'atRef' },
  { text: 'charAt()', ref: 'charAtRef' },
  { text: 'charCodeAt()', ref: 'charCodeAtRef' },
  { text: 'codePointAt()', ref: 'codePointAtRef' },
  { text: 'concat()', ref: 'concatRef' },
  { text: 'endsWith()', ref: 'endsWithRef' },
  { text: 'fromCharCode()', ref: 'fromCharCodeRef' },
  { text: 'fromCodePoint()', ref: 'fromCodePointRef' },
  { text: 'includes()', ref: 'includesRef' },
  { text: 'indexOf()', ref: 'indexOfRef' },
  { text: 'lastIndexOf()', ref: 'lastIndexOfRef' },
  { text: 'localeCompare()', ref: 'localeCompareRef' },
  { text: 'match()', ref: 'matchRef' },
  { text: 'matchAll()', ref: 'matchAllRef' },
  { text: 'normalize()', ref: 'normalizeRef' },
  { text: 'padEnd()', ref: 'padEndRef' },
  { text: 'padStart()', ref: 'padStartRef' },
  { text: 'raw()', ref: 'rawRef' },
  { text: 'repeat()', ref: 'repeatRef' },
  { text: 'replace()', ref: 'replaceRef' },
  { text: 'replaceAll()', ref: 'replaceAllRef' },
  { text: 'search()', ref: 'searchRef' },
  { text: 'slice()', ref: 'sliceRef' },
  { text: 'split()', ref: 'splitRef' },
  { text: 'startsWith()', ref: 'startsWithRef' },
  { text: 'substring()', ref: 'substringRef' },
  { text: 'toLocaleLowerCase()', ref: 'toLocaleLowerCaseRef' },
  { text: 'toLocaleUpperCase()', ref: 'toLocaleUpperCaseRef' },
  { text: 'toLowerCase()', ref: 'toLowerCaseRef' },
  { text: 'toString()', ref: 'toStringRef' },
  { text: 'toUpperCase()', ref: 'toUpperCaseRef' },
  { text: 'trim()', ref: 'trimRef' },
  { text: 'trimEnd()', ref: 'trimEndRef' },
  { text: 'trimStart()', ref: 'trimStartRef' },
  { text: 'valueOf()', ref: 'valueOfRef' },
];

export default metodosString;
